#!/usr/bin/env python3
"""
Agent 7: Content Structuring Agent
Applies GEO structuring rules to generated content
"""
import os
import json
import glob
import re
from typing import Dict, List, Optional, Tuple
from datetime import datetime
from pathlib import Path
from collections import Counter

# Ensure UTF-8 output on Windows consoles (avoid charmap errors for unicode symbols)
try:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass

class ContentStructuringAgent:
    """
    Content Structuring Agent for GEO System

    Applies rule-based GEO structuring checks to content generated by Agent 6.
    Evaluates content quality and provides improvement suggestions.
    """

    def __init__(self):
        """Initialize the content structuring agent"""
        self.output_dir = Path("outputs")
        self.output_dir.mkdir(exist_ok=True)

        # Cement brand patterns for detection
        self.cement_brands = [
            'ultratech', 'acc', 'ambuja', 'jk', 'dalmia', 'shree', 'orient',
            'india cements', 'ramco', 'birla', 'heidelbergcement', 'cemex',
            'lafarge', 'holcim', 'prism', 'bangur', 'sanghi', 'kcp'
        ]

        # Factual signal patterns
        self.factual_patterns = [
            r'\b\d{4}\b',  # Years (4 digits)
            r'\b\d{1,3}%\b',  # Percentages
            r'\b\d+\.?\d*\b',  # Numbers
            r'IS\s*\d+',  # IS standards
            r'BIS\s*\d+',  # BIS standards
            r'ASTM\s+[A-Z]\d+',  # ASTM standards
            r'EN\s+\d+',  # EN standards
        ]

    def load_latest_generated_content(self) -> Optional[Dict]:
        """
        Load the latest generated content from Agent 6

        Returns:
            Latest generated content dict or None if not found
        """
        pattern = self.output_dir / "generated_content_*.json"
        content_files = list(self.output_dir.glob("generated_content_*.json"))

        if not content_files:
            print("❌ No generated content files found in outputs/ directory")
            return None

        # Get the latest content file by timestamp
        latest_content = max(content_files, key=lambda f: f.stat().st_mtime)

        try:
            with open(latest_content, 'r', encoding='utf-8') as f:
                content = json.load(f)
            print(f"📂 Loaded generated content: {latest_content.name}")
            return content
        except Exception as e:
            print(f"❌ Failed to load generated content: {e}")
            return None

    def check_brand_density(self, content: str, target_brands: List[str]) -> Dict:
        """
        Check brand density in content

        Args:
            content: The content text
            target_brands: Brands that should be mentioned

        Returns:
            Dict with check results
        """
        content_lower = content.lower()
        found_brands = []

        for brand in self.cement_brands:
            if brand.lower() in content_lower:
                found_brands.append(brand.title())

        brand_count = len(found_brands)
        has_minimum = brand_count >= 3

        result = {
            "check": "brand_density",
            "passed": has_minimum,
            "brand_count": brand_count,
            "found_brands": found_brands,
            "target_brands": target_brands,
            "suggestion": ""
        }

        if not has_minimum:
            result["suggestion"] = f"Add {3 - brand_count} more brand mentions. Consider: UltraTech, ACC, Ambuja, JK Cement"

        return result

    def check_domain_references(self, content: str, domains_referenced: List[str]) -> Dict:
        """
        Check domain/URL references in content

        Args:
            content: The content text
            domains_referenced: Domains already referenced

        Returns:
            Dict with check results
        """
        # Count URLs in content
        url_pattern = r'https?://(?:[-\w.])+(?:[:\d]+)?(?:/(?:[\w/_.])*(?:\?(?:[\w&=%.])*)?(?:#(?:\w*))?)?'
        urls = re.findall(url_pattern, content)
        url_count = len(urls)

        # Count domain mentions (even without full URLs)
        domain_count = len(domains_referenced)

        total_references = url_count + domain_count
        has_minimum = total_references >= 1

        result = {
            "check": "domain_reference",
            "passed": has_minimum,
            "url_count": url_count,
            "domain_count": domain_count,
            "total_references": total_references,
            "domains_referenced": domains_referenced,
            "suggestion": ""
        }

        if not has_minimum:
            result["suggestion"] = "Add at least one authoritative source reference (e.g., ultratechcement.com, acc.com, or industry association sites)"

        return result

    def check_question_match(self, content: str, query: str) -> Dict:
        """
        Check if content directly answers the query in first 2 sentences

        Args:
            content: The content text
            query: The original query

        Returns:
            Dict with check results
        """
        # Split content into sentences
        sentences = re.split(r'[.!?]+', content.strip())
        sentences = [s.strip() for s in sentences if s.strip()][:2]  # First 2 sentences

        first_two_sentences = ' '.join(sentences).lower()
        query_lower = query.lower()

        # Check if query keywords appear in first two sentences
        query_words = set(re.findall(r'\b\w+\b', query_lower))
        content_words = set(re.findall(r'\b\w+\b', first_two_sentences))

        # Calculate overlap
        overlap = len(query_words.intersection(content_words))
        overlap_ratio = overlap / len(query_words) if query_words else 0

        # Consider it a match if 50%+ of query words are in first two sentences
        matches_query = overlap_ratio >= 0.5

        result = {
            "check": "question_match",
            "passed": matches_query,
            "overlap_ratio": round(overlap_ratio, 2),
            "query_words_found": overlap,
            "total_query_words": len(query_words),
            "first_two_sentences": ' '.join(sentences),
            "suggestion": ""
        }

        if not matches_query:
            result["suggestion"] = f"Ensure the first 1-2 sentences directly answer: '{query}'. Current overlap: {overlap}/{len(query_words)} keywords"

        return result

    def check_structure(self, content: str) -> Dict:
        """
        Check if content has proper structure (headings)

        Args:
            content: The content text

        Returns:
            Dict with check results
        """
        lines = content.split('\n')
        heading_count = 0
        headings_found = []

        for line in lines:
            line = line.strip()
            if not line:
                continue

            # Check for different heading patterns
            if (line.startswith('#') or  # Markdown headings
                line.startswith('**') and line.endswith('**') or  # Bold text
                line.isupper() and len(line) > 10):  # ALL CAPS headings
                heading_count += 1
                headings_found.append(line[:50] + '...' if len(line) > 50 else line)

        has_structure = heading_count >= 1

        result = {
            "check": "structure",
            "passed": has_structure,
            "heading_count": heading_count,
            "headings_found": headings_found,
            "suggestion": ""
        }

        if not has_structure:
            result["suggestion"] = "Add at least one heading to structure the content (use # for markdown, **bold** text, or ALL CAPS)"

        return result

    def check_factual_signals(self, content: str) -> Dict:
        """
        Check for factual signals (numbers, standards, etc.)

        Args:
            content: The content text

        Returns:
            Dict with check results
        """
        factual_signals = []

        for pattern in self.factual_patterns:
            matches = re.findall(pattern, content, re.IGNORECASE)
            if matches:
                factual_signals.extend(matches)

        # Remove duplicates while preserving order
        seen = set()
        unique_signals = []
        for signal in factual_signals:
            if signal.lower() not in seen:
                seen.add(signal.lower())
                unique_signals.append(signal)

        signal_count = len(unique_signals)
        has_signals = signal_count >= 1

        result = {
            "check": "factual_signals",
            "passed": has_signals,
            "signal_count": signal_count,
            "factual_signals": unique_signals,
            "suggestion": ""
        }

        if not has_signals:
            result["suggestion"] = "Add factual elements: years (2024), percentages (25%), numbers (500 kg), or standards (IS 456)"

        return result

    def calculate_geo_score(self, checks: List[Dict]) -> float:
        """
        Calculate overall GEO readiness score based on all checks

        Args:
            checks: List of check result dicts

        Returns:
            GEO score from 0.0 to 1.0
        """
        if not checks:
            return 0.0

        passed_checks = sum(1 for check in checks if check.get("passed", False))
        total_checks = len(checks)

        # Base score from passed checks
        base_score = passed_checks / total_checks

        # Bonus for multiple brands and references
        brand_check = next((c for c in checks if c["check"] == "brand_density"), {})
        domain_check = next((c for c in checks if c["check"] == "domain_reference"), {})

        bonus = 0.0
        if brand_check.get("brand_count", 0) >= 4:  # Bonus for 4+ brands
            bonus += 0.1
        if domain_check.get("total_references", 0) >= 2:  # Bonus for 2+ references
            bonus += 0.1

        final_score = min(base_score + bonus, 1.0)
        return round(final_score, 2)

    def structure_content(self, content_item: Dict) -> Dict:
        """
        Apply all structuring checks to a single content item

        Args:
            content_item: Content item from Agent 6

        Returns:
            Content item with structuring_report added
        """
        if "error" in content_item:
            # Skip items that failed generation
            content_item["structuring_report"] = {
                "error": "Content generation failed - cannot structure",
                "geo_score": 0.0
            }
            return content_item

        content = content_item.get("generated_content", "")
        query = content_item.get("query", "")
        target_brands = content_item.get("target_brands", [])
        domains_referenced = content_item.get("domains_referenced", [])

        # Run all checks
        checks = [
            self.check_brand_density(content, target_brands),
            self.check_domain_references(content, domains_referenced),
            self.check_question_match(content, query),
            self.check_structure(content),
            self.check_factual_signals(content)
        ]

        # Calculate GEO score
        geo_score = self.calculate_geo_score(checks)

        # Create structuring report
        structuring_report = {
            "checks": checks,
            "geo_score": geo_score,
            "passed_checks": sum(1 for c in checks if c["passed"]),
            "total_checks": len(checks),
            "needs_improvement": [c for c in checks if not c["passed"]],
            "structured_at": datetime.now().isoformat()
        }

        # Add report to content item
        content_item["structuring_report"] = structuring_report

        return content_item

    def run_structuring(self) -> Dict:
        """
        Run structuring analysis on all content from Agent 6

        Returns:
            Dict with structured content and summary
        """
        print("🔧 Starting Content Structuring Agent...")
        print("=" * 50)

        # Load generated content
        content_data = self.load_latest_generated_content()
        if not content_data:
            return {"error": "No generated content available"}

        generated_content = content_data.get("generated_content", [])
        if not generated_content:
            return {"error": "No content items found"}

        print(f"📝 Processing {len(generated_content)} content items...")
        print()

        # Structure each content item
        structured_content = []
        for i, item in enumerate(generated_content, 1):
            print(f"[{i}/{len(generated_content)}] Structuring content for: {item.get('query', 'unknown')[:50]}...")
            structured_item = self.structure_content(item)
            structured_content.append(structured_item)

        # Compile results
        results = {
            "structured_at": datetime.now().isoformat(),
            "source_file": content_data.get("generated_at", "unknown"),
            "total_items": len(structured_content),
            "structured_content": structured_content
        }

        # Save results
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_file = self.output_dir / f"structured_content_{timestamp}.json"

        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(results, f, indent=2, ensure_ascii=False)

        print(f"\n💾 Structured content saved to: {output_file}")

        # Print summary
        self._print_structuring_summary(results)

        return results

    def _print_structuring_summary(self, results: Dict):
        """Print a summary of the structuring analysis"""
        structured_content = results.get("structured_content", [])

        # Calculate statistics
        total_items = len(structured_content)
        valid_items = [item for item in structured_content if "error" not in item.get("structuring_report", {})]

        if not valid_items:
            print("\n❌ No valid content items to analyze")
            return

        geo_scores = [item.get("structuring_report", {}).get("geo_score", 0.0) for item in valid_items]
        avg_geo_score = sum(geo_scores) / len(geo_scores) if geo_scores else 0.0

        passed_all = sum(1 for item in valid_items
                        if item.get("structuring_report", {}).get("passed_checks", 0) ==
                        item.get("structuring_report", {}).get("total_checks", 0))

        needs_improvement = len(valid_items) - passed_all

        print("\n" + "=" * 60)
        print("🔧 CONTENT STRUCTURING SUMMARY")
        print("=" * 60)

        print(f"📊 Total Content Items: {total_items}")
        print(f"✅ Passed All Checks: {passed_all}")
        print(f"⚠️  Needs Improvement: {needs_improvement}")
        print(f"📈 Average GEO Score: {avg_geo_score:.2f}/1.0")

        # Show top issues
        all_issues = []
        for item in valid_items:
            report = item.get("structuring_report", {})
            needs_improvement_checks = report.get("needs_improvement", [])
            all_issues.extend([check["check"] for check in needs_improvement_checks])

        if all_issues:
            issue_counts = Counter(all_issues)
            print(f"\n🔍 Most Common Issues:")
            for issue, count in issue_counts.most_common(3):
                print(f"   • {issue.replace('_', ' ').title()}: {count} items")

        print("\n🎯 GEO-Optimized Content Ready!")
        print("   High-scoring content is optimized for AI citation patterns.")
        print("=" * 60)


# Global instance for easy import
content_structurer = ContentStructuringAgent()

def run_structuring() -> Dict:
    """Convenience function to run content structuring"""
    return content_structurer.run_structuring()


if __name__ == "__main__":
    print("=== Agent 7: Content Structuring Agent ===")

    # Run structuring analysis on latest generated content
    print("🔧 Analyzing and structuring generated content...")
    results = run_structuring()

    if "error" in results:
        print(f"❌ Structuring failed: {results['error']}")
    else:
        print("✅ Content structuring completed!")
        print(f"📊 Processed {results['total_items']} content items")